import Header from '@/layout/header/Header';
import './globals.css'
import { Noto_Sans_KR } from 'next/font/google'
import Providers from '@/store/provider';

const notoSansKr = Noto_Sans_KR({
  weight: ['100', '400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
